MODULE_BINS := examples/pp_discover \
               examples/pp_pci \
               examples/pp_read \
               examples/pp_fuse \
               examples/pp_server \
               examples/pp_client

BINS += $(MODULE_BINS)
CLEANS += examples/cmdline.o

$(MODULE_BINS): examples/cmdline.o

examples/pp_fuse: TGT_LDLIBS_STATIC += -lfuse
examples/pp_fuse: TGT_LDLIBS_DYNAMIC += -lpthread -ldl -lrt

