SRCS += util/bignum.cc \
        util/bit_buffer.cc \
        util/log.cc

TESTS += util/tests/bignum_test \
         util/tests/bit_buffer_test \
         util/tests/filesystem_test \
         util/tests/keyed_vector_test \
         util/tests/pointer_test \
         util/tests/printfxx_test \
         util/tests/regex_test \
         util/tests/sockets_test \
         util/tests/symbol_table_test \
         util/tests/syserror_test
         #util/tests/shared_object_test

util/tests/bignum_test: util/bignum.o util/bit_buffer.o
util/tests/bit_buffer_test: util/bit_buffer.o
