OBJS += devices/all_devices.o

MODULE_SRCS := devices/global.cc \
               devices/pci/pci.cc \
               devices/pci/generic_device.cc \
               devices/cpu/cpu.cc \
               devices/cpuid/cpuid.cc \
               devices/cpuid/generic_device.cc \
               devices/msr/msr.cc \
               devices/msr/generic_device.cc \
               devices/amd/k8.cc
MODULE_OBJS := $(MODULE_SRCS:.cc=.o)

CLEANS += $(MODULE_OBJS)

devices/all_devices.o: $(MODULE_OBJS)
	$(CXX) $(LDFLAGS) -nostdlib -Wl,-r -o $@ $^
