OBJS += devices/all_devices.o

MODULE_SRCS := \
	devices/global.cpp \
	devices/pci/pci.cpp \
	devices/pci/generic_device.cpp \
	devices/cpu/cpu.cpp \
	devices/cpuid/cpuid.cpp \
	devices/cpuid/generic_device.cpp \
	devices/msr/msr.cpp \
	devices/msr/generic_device.cpp \
	devices/amd/k8.cpp
MODULE_OBJS := $(MODULE_SRCS:.cpp=.o)

CLEANS += $(MODULE_OBJS)

devices/all_devices.o: $(MODULE_OBJS)
	$(CXX) $(LDFLAGS) -nostdlib -Wl,-r -o $@ $^
