MODULE_BINS := examples/hwpp_discover \
               examples/hwpp_pci \
               examples/hwpp_read \
               examples/hwpp_fuse \
               examples/hwpp_server \
               examples/hwpp_client

BINS += $(MODULE_BINS)
CLEANS += examples/cmdline.o

$(MODULE_BINS): examples/cmdline.o

examples/hwpp_fuse: TGT_LDLIBS_STATIC += -lfuse
examples/hwpp_fuse: TGT_LDLIBS_DYNAMIC += -lpthread -ldl -lrt

